/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        heading: ['Outfit', 'sans-serif'],
        apple: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"SF Pro Display"', '"Inter"', 'sans-serif'],
      },
      colors: {
        'smart-indigo': '#1d4ed8',
        'smart-indigo-hover': '#1e40af',
        'friendly-orange': '#ff7a30',
        'friendly-orange-hover': '#ea580c',
        'light-bg': '#f8fafc',
        'ink-dark': '#0f172a',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        // BoardUI tokens
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-white': 'var(--color-text-white)',
        'background-primary-default': 'var(--color-background-primary-default)',
        'background-primary-hover': 'var(--color-background-primary-hover)',
        'background-primary-active': 'var(--color-background-primary-active)',
        'background-secondary-default': 'var(--color-background-secondary-default)',
        'background-secondary-hover': 'var(--color-background-secondary-hover)',
        'background-tertiary-default': 'var(--color-background-tertiary-default)',
        'background-tertiary-hover': 'var(--color-background-tertiary-hover)',
        'background-inner-default': 'var(--color-background-inner-default)',
        'stat-card-icon-background': 'var(--color-stat-card-icon-background)',
        'segmented-control-background': 'var(--color-segmented-control-background)',
        'segmented-control-selected-background': 'var(--color-segmented-control-selected-background)',
        'border-button-default': 'var(--color-border-button-default)',
        'border-button-hover': 'var(--color-border-button-hover)',
        'border-focus-ring': 'var(--color-border-focus-ring)',
        'border-table': 'var(--color-border-table)',
        'separator-border': 'var(--color-separator-border)',
        'status-lime-background': 'var(--color-status-lime-background)',
        'status-lime-text': 'var(--color-status-lime-text)',
        'status-yellow-background': 'var(--color-status-yellow-background)',
        'status-yellow-text': 'var(--color-status-yellow-text)',
        'status-rose-background': 'var(--color-status-rose-background)',
        'status-rose-text': 'var(--color-status-rose-text)',
        'status-cyan-background': 'var(--color-status-cyan-background)',
        'status-cyan-text': 'var(--color-status-cyan-text)',
        'status-blue-background': 'var(--color-status-blue-background)',
        'status-blue-text': 'var(--color-status-blue-text)',
        'status-purple-background': 'var(--color-status-purple-background)',
        'status-purple-text': 'var(--color-status-purple-text)',
        'foreground-icon-primary': 'var(--color-foreground-icon-primary)',
        'foreground-icon-secondary': 'var(--color-foreground-icon-secondary)',
        'foreground-icon-tertiary': 'var(--color-foreground-icon-tertiary)',
      },
      boxShadow: {
        '2xs': 'var(--shadow-2xs, 0 1px 2px 0 rgb(0 0 0 / 0.05))',
        'xs': 'var(--shadow-xs, 0 1px 2px 0 rgb(0 0 0 / 0.05))',
        'card': 'var(--shadow-card, 0 1px 1px 0 rgb(0 0 0 / 0.05))',
        'dropdown': 'var(--shadow-dropdown, 0 4px 6px -1px rgb(0 0 0 / 0.1))',
      },
      borderRadius: {
        '2lg': 'var(--radius-2lg, 10px)',
        xl: 'var(--radius)',
        lg: 'calc(var(--radius) - 2px)',
        md: 'calc(var(--radius) - 4px)',
      }
    },
  },
  plugins: [],
}
